import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "SF Mono Powerline"
#family = "JetBrainsMonoNL NF"
style = "Regular"

[window]
dynamic_padding = false
opacity = 0.65

[window.padding]
x = 10
y = 10

[cursor]
style = { shape = "Underline", blinking = "on" }
