var categories = ["Happy", "Love", "Cat", "Sleepy", "Sad", "Angry", "Shrug", "Party", "Cute", "Wink", "Excited", "Cool", "Sorry", "Weird"];

var entries = [
    { cat: "Happy", ch: "(◍•ᴗ•◍)", tags: "happy cute smile joy cheerful" },
    { cat: "Happy", ch: "(＾▽＾)", tags: "happy smile joy glad" },
    { cat: "Happy", ch: "(◕‿◕)", tags: "happy smile pleased" },
    { cat: "Happy", ch: "(´▽`)", tags: "happy content satisfied" },
    { cat: "Happy", ch: "(＾ω＾)", tags: "happy smile cheerful" },
    { cat: "Happy", ch: "(⌒‿⌒)", tags: "happy smile joy" },
    { cat: "Happy", ch: "(•‿•)", tags: "smile happy" },
    { cat: "Happy", ch: "ヽ(´▽`)/", tags: "happy cheer hooray" },
    { cat: "Happy", ch: "(＾∇＾)", tags: "happy smile" },
    { cat: "Happy", ch: "(ᵔᴥᵔ)", tags: "happy doggie puppy" },
    { cat: "Happy", ch: "(◔◡◔)", tags: "happy sly pleased" },
    { cat: "Happy", ch: "(≧◠‿◠≦)", tags: "happy yay grin" },
    { cat: "Happy", ch: "(＾▽＾)／", tags: "happy wave hello" },
    { cat: "Happy", ch: "＼(＾O＾)／", tags: "happy cheer hooray" },

    { cat: "Love", ch: "(♥ω♥*)", tags: "love heart" },
    { cat: "Love", ch: "(♡˙︶˙♡)", tags: "love affection" },
    { cat: "Love", ch: "(´,,•ω•,,)♡", tags: "love blush crush" },
    { cat: "Love", ch: "( ˘ ³˘)♥", tags: "kiss love" },
    { cat: "Love", ch: "(♥_♥)", tags: "heart eyes crush" },
    { cat: "Love", ch: "(❤ω❤)", tags: "love heart" },
    { cat: "Love", ch: "(｡♥‿♥｡)", tags: "love sweetheart" },
    { cat: "Love", ch: "(´ε｀ )♡", tags: "kiss smooch" },
    { cat: "Love", ch: "(´ω｀*)", tags: "love dreamy" },
    { cat: "Love", ch: "(つ≧▽≦)つ", tags: "hug embrace" },
    { cat: "Love", ch: "(づ｡◕‿‿◕｡)づ", tags: "hug cuddle" },
    { cat: "Love", ch: "(づ￣ ³￣)づ", tags: "hug love" },
    { cat: "Love", ch: "(￣ε￣＠)", tags: "kiss love" },
    { cat: "Love", ch: "(っ˘ڡ˘ς)", tags: "smooch kiss" },
    { cat: "Love", ch: "(・ε・)", tags: "kiss mwah" },
    { cat: "Love", ch: "♪～(´ε｀ )", tags: "love singing" },
    { cat: "Love", ch: "(＠＾◡＾)", tags: "love soft" },
    { cat: "Love", ch: "(◍•ᴗ•◍)♡", tags: "love cute heart" },
    { cat: "Love", ch: "(♡´艸`)", tags: "love giggle heart" },

    { cat: "Cat", ch: "(=^･ω･^=)", tags: "cat neko kitty" },
    { cat: "Cat", ch: "(=^･ｪ･^=)", tags: "cat kitty" },
    { cat: "Cat", ch: "(=^-ω-^=)", tags: "cat happy" },
    { cat: "Cat", ch: "(=^‥^=)", tags: "cat" },
    { cat: "Cat", ch: "(ΦωΦ)", tags: "cat curious" },
    { cat: "Cat", ch: "(=^ω^=)", tags: "cat happy" },
    { cat: "Cat", ch: "ฅ(•ㅅ•❁)ฅ", tags: "cat paws cute" },
    { cat: "Cat", ch: "ฅ(^•ﻌ•^)ฅ", tags: "cat paws kitty" },
    { cat: "Cat", ch: "(=^・ω・^=)", tags: "cat" },
    { cat: "Cat", ch: "(=TェT=)", tags: "cat sad" },
    { cat: "Cat", ch: "(=^･^=)", tags: "cat" },
    { cat: "Cat", ch: "(₌ㅅ₌)", tags: "cat" },
    { cat: "Cat", ch: "(=;ω;=)", tags: "cat cry" },
    { cat: "Cat", ch: "(=ΦᆽΦ=)", tags: "cat sleepy" },
    { cat: "Cat", ch: "(=ΦωΦ=)", tags: "cat owl" },

    { cat: "Sleepy", ch: "(－ω－)", tags: "sleepy tired" },
    { cat: "Sleepy", ch: "(￣o￣)", tags: "sleepy zzz" },
    { cat: "Sleepy", ch: "(´-ω-`)", tags: "sleepy drowsy" },
    { cat: "Sleepy", ch: "(-,-)", tags: "zzz" },
    { cat: "Sleepy", ch: "(¦3[▓▓]", tags: "zzz sleeping" },
    { cat: "Sleepy", ch: "(－_－)", tags: "zzz sleepy" },
    { cat: "Sleepy", ch: "(。－ω－)zzz", tags: "sleep goodnight" },
    { cat: "Sleepy", ch: "(´〜`)", tags: "sleepy" },
    { cat: "Sleepy", ch: "( -_・)", tags: "sleepy tired" },
    { cat: "Sleepy", ch: "(__)..zzzZZ", tags: "sleep" },
    { cat: "Sleepy", ch: "(～￣▽￣)～", tags: "sleepy content" },
    { cat: "Sleepy", ch: "(￣ ￣|||)", tags: "exhausted" },
    { cat: "Sleepy", ch: "(´｡• ω •｡`)", tags: "sleepy soft" },
    { cat: "Sleepy", ch: "(＝ω＝。)", tags: "sleepy" },
    { cat: "Sleepy", ch: "(Ｕ o Ｕ*)", tags: "sleepy cute" },

    { cat: "Sad", ch: "(´；ω；`)", tags: "sad cry" },
    { cat: "Sad", ch: "(T_T)", tags: "cry tears" },
    { cat: "Sad", ch: "(；ω；)", tags: "cry weep" },
    { cat: "Sad", ch: "(╥﹏╥)", tags: "cry sad" },
    { cat: "Sad", ch: "(っ˘̩╭╮˘̩)っ", tags: "sad" },
    { cat: "Sad", ch: "(´;ω;`)", tags: "sad" },
    { cat: "Sad", ch: "(｡•́︿•̀｡)", tags: "sad" },
    { cat: "Sad", ch: "(◞‸◟)", tags: "sad" },
    { cat: "Sad", ch: "(｡╯︵╰｡)", tags: "sad" },
    { cat: "Sad", ch: "(ಥ﹏ಥ)", tags: "cry sob" },
    { cat: "Sad", ch: "(ಥ_ಥ)", tags: "cry" },
    { cat: "Sad", ch: "(＞﹏＜)", tags: "sad anguished" },
    { cat: "Sad", ch: "(;_;)", tags: "cry" },
    { cat: "Sad", ch: "(μ_μ)", tags: "cry" },
    { cat: "Sad", ch: "(´；д；`)", tags: "sad" },

    { cat: "Angry", ch: "(；￣Д￣)", tags: "angry" },
    { cat: "Angry", ch: "(ノಠ益ಠ)ノ", tags: "angry throw" },
    { cat: "Angry", ch: "(凸ಠ益ಠ)凸", tags: "angry rude" },
    { cat: "Angry", ch: "(╬ Ò﹏Ó)", tags: "angry" },
    { cat: "Angry", ch: "(｀Д´)", tags: "angry" },
    { cat: "Angry", ch: "(ಠ_ಠ)", tags: "disapproval judge" },
    { cat: "Angry", ch: "(╬▔皿▔)╬", tags: "angry" },
    { cat: "Angry", ch: "٩(╬ʘ益ʘ╬)۶", tags: "angry" },
    { cat: "Angry", ch: "(¬_¬\")", tags: "annoyed" },
    { cat: "Angry", ch: "(ー_ー゛)", tags: "annoyed" },
    { cat: "Angry", ch: "凸(￣ヘ￣)", tags: "angry rude" },
    { cat: "Angry", ch: "(╯°□°)╯︵ ┻━┻", tags: "tableflip rage" },
    { cat: "Angry", ch: "┬─┬ノ( º _ ºノ)", tags: "tablefix calm" },
    { cat: "Angry", ch: "(╬ಠ益ಠ)", tags: "angry" },
    { cat: "Angry", ch: "(＃￣ω￣)", tags: "annoyed" },
    { cat: "Angry", ch: "(；一_一)", tags: "annoyed" },

    { cat: "Shrug", ch: "¯\\_(ツ)_/¯", tags: "shrug dunno" },
    { cat: "Shrug", ch: "ヽ(ー_ー )ノ", tags: "shrug whatever" },
    { cat: "Shrug", ch: "¯\\(◉‿◉)/¯", tags: "shrug" },
    { cat: "Shrug", ch: "┐(‘～` )┌", tags: "shrug" },
    { cat: "Shrug", ch: "┐( ∵ )┌", tags: "shrug" },
    { cat: "Shrug", ch: "¯\\_ʘ‿ʘ_/¯", tags: "shrug" },
    { cat: "Shrug", ch: "ヘ(´-`)ヘ", tags: "shrug sigh" },
    { cat: "Shrug", ch: "(ㆆ _ ㆆ)", tags: "shrug" },
    { cat: "Shrug", ch: "ヽ(￣д￣)ノ", tags: "shrug whatever" },
    { cat: "Shrug", ch: "(￣▽￣)ノ", tags: "shrug wave" },

    { cat: "Party", ch: "(ﾉ◕ヮ◕)ﾉ*:・゚✧", tags: "party sparkles" },
    { cat: "Party", ch: "└(^o^)┐", tags: "party dance" },
    { cat: "Party", ch: "(^o^)/", tags: "party cheer yay" },
    { cat: "Party", ch: "٩(◕‿◕)۶", tags: "party celebrate" },
    { cat: "Party", ch: "(ﾟ▽ﾟ)/", tags: "dance party" },
    { cat: "Party", ch: "♪└(´▽`)┘♪", tags: "dance music" },
    { cat: "Party", ch: "ヽ(°〇°)ﾉ", tags: "party wow" },
    { cat: "Party", ch: "(★≧▽≦)★", tags: "party excited" },
    { cat: "Party", ch: "✨ヽ(´▽`)/✨", tags: "party sparkle" },
    { cat: "Party", ch: "٩(ˊᗜˋ*)و", tags: "party celebrate" },
    { cat: "Party", ch: "(ノ°▽°)ノ", tags: "party dance" },
    { cat: "Party", ch: "♪(´ε｀ )", tags: "dance music" },

    { cat: "Cute", ch: "(๑˃ᴗ˂)ﻭ", tags: "cute adorable" },
    { cat: "Cute", ch: "(｡◕‿◕｡)", tags: "cute" },
    { cat: "Cute", ch: "(´• ω •`)", tags: "cute shy" },
    { cat: "Cute", ch: "ʕ•ᴥ•ʔ", tags: "cute bear teddy" },
    { cat: "Cute", ch: "(っ˘ω˘ς)", tags: "cute blush" },
    { cat: "Cute", ch: "(｡･ω･｡)", tags: "cute" },
    { cat: "Cute", ch: "(●´ω`●)", tags: "cute" },
    { cat: "Cute", ch: "(◠‿◠)", tags: "cute" },
    { cat: "Cute", ch: "ヾ(＾∇＾)", tags: "cute" },
    { cat: "Cute", ch: "(≧◡≦)", tags: "cute" },
    { cat: "Cute", ch: "( ◜◡＾)っ", tags: "cute" },
    { cat: "Cute", ch: "(っ´▽`)っ", tags: "cute" },
    { cat: "Cute", ch: "(｡•̀ᴗ-)✧", tags: "cute wink" },
    { cat: "Cute", ch: "(´･ω･`)", tags: "cute" },
    { cat: "Cute", ch: "(´｡• ᵕ •｡`)", tags: "cute sweet" },

    { cat: "Wink", ch: "(◔‿◔)", tags: "wink" },
    { cat: "Wink", ch: "(-‿◦)", tags: "wink" },
    { cat: "Wink", ch: "(＾艸＾)", tags: "smirk teasing" },
    { cat: "Wink", ch: "(☞ﾟ∀ﾟ)☞", tags: "wink point" },
    { cat: "Wink", ch: "(•̀ω•́)✧", tags: "wink determined" },
    { cat: "Wink", ch: "(￢_￢)", tags: "wink sideeye" },
    { cat: "Wink", ch: "(◕‿◕)✧", tags: "wink" },
    { cat: "Wink", ch: "(≖‿≖)", tags: "wink" },
    { cat: "Wink", ch: "(¬‿¬)", tags: "sly" },
    { cat: "Wink", ch: "(‾⌣‾)", tags: "wink" },
    { cat: "Wink", ch: "(｡￫‿￩｡)", tags: "wink cute" },
    { cat: "Wink", ch: "(￣‿￣)", tags: "wink" },
    { cat: "Wink", ch: "(´｡•ᴗ•｡`)", tags: "wink" },

    { cat: "Excited", ch: "(≧▽≦)", tags: "excited yay grin" },
    { cat: "Excited", ch: "(ノ≧∀≦)ノ", tags: "excited" },
    { cat: "Excited", ch: "(ﾉ>ω<)ﾉ", tags: "excited" },
    { cat: "Excited", ch: "(๑>ᴗ<๑)", tags: "excited" },
    { cat: "Excited", ch: "٩(≧▽≦)۶", tags: "excited" },
    { cat: "Excited", ch: "(☆▽☆)", tags: "excited stars" },
    { cat: "Excited", ch: "(*≧ω≦*)", tags: "excited" },
    { cat: "Excited", ch: "(ノ´∀`)ノ", tags: "excited" },
    { cat: "Excited", ch: "(≧∇≦)ﾉ", tags: "excited" },
    { cat: "Excited", ch: "(●≧ω≦)９", tags: "excited" },

    { cat: "Cool", ch: "(•̀ᴗ•́)و", tags: "cool confident" },
    { cat: "Cool", ch: "٩(•̀ᴗ•́)و", tags: "cool determined" },
    { cat: "Cool", ch: "(ง •̀_•́)ง", tags: "determined focused" },
    { cat: "Cool", ch: "(⌐■_■)", tags: "cool shades" },
    { cat: "Cool", ch: "( •_•)>⌐■-■", tags: "cool glasses" },
    { cat: "Cool", ch: "(｀・ω・´)", tags: "confident" },
    { cat: "Cool", ch: "(▰˘◡˘▰)", tags: "chill relaxed" },
    { cat: "Cool", ch: "(￣ヘ￣)", tags: "smug" },
    { cat: "Cool", ch: "(´∀`)", tags: "chill relaxed" },
    { cat: "Cool", ch: "ヾ(´∀`)ノ", tags: "chill easygoing" },
    { cat: "Cool", ch: "(・∀・)", tags: "chill" },
    { cat: "Cool", ch: "(￣ω￣)", tags: "smug satisfied" },

    { cat: "Sorry", ch: "m(_ _)m", tags: "apologize bow" },
    { cat: "Sorry", ch: "<(_ _)>", tags: "apologize bow" },
    { cat: "Sorry", ch: "(シ_ _)シ", tags: "apologize" },
    { cat: "Sorry", ch: "(＞人＜;)", tags: "sorry plead" },
    { cat: "Sorry", ch: "(ノ﹏ヽ)", tags: "sorry" },
    { cat: "Sorry", ch: "(・人・)", tags: "apologize" },
    { cat: "Sorry", ch: "(╯﹏╰)", tags: "sorry" },
    { cat: "Sorry", ch: "(人_ _)", tags: "bow apologize" },
    { cat: "Sorry", ch: "m(._.)m", tags: "apologize" },
    { cat: "Sorry", ch: "( ノωヽ、)", tags: "sorry" },
    { cat: "Sorry", ch: "｡ﾟ(ﾟ´Д｀ﾟ)ﾟ｡", tags: "sorry cry" },

    { cat: "Weird", ch: "( ͡° ͜ʖ ͡°)", tags: "lenny" },
    { cat: "Weird", ch: "( ͡☉ ͜ʖ ͡☉)", tags: "lenny" },
    { cat: "Weird", ch: "ಠ_ರೃ", tags: "weird" },
    { cat: "Weird", ch: "(o_O)", tags: "huh confused" },
    { cat: "Weird", ch: "(O_o)", tags: "huh confused" },
    { cat: "Weird", ch: "(O_O)", tags: "shocked" },
    { cat: "Weird", ch: "(o_o)", tags: "huh" },
    { cat: "Weird", ch: "(・_・;)", tags: "awkward" },
    { cat: "Weird", ch: "(ーー;)", tags: "facepalm" },
    { cat: "Weird", ch: "(×_×)", tags: "dead fainted" },
    { cat: "Weird", ch: "(─.─||)", tags: "facepalm" },
    { cat: "Weird", ch: "(￣△￣)", tags: "awkward" },
    { cat: "Weird", ch: "ヾ(。ヘ°)", tags: "heh" },
    { cat: "Weird", ch: "(・_・)ヾ", tags: "awkward" },
    { cat: "Weird", ch: "(≖_≖)", tags: "stare" },
    { cat: "Weird", ch: "(ʘ‿ʘ)", tags: "weird" }
];
