-- AUTOGENERATED HYPR CONFIG.
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.lua AND EDIT IT,
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

-- Sourcing your separate files
require("env")
require("mocha")
require("monitors")
require("startup")
require("windowrules")
require("workspaces")
require("keybinds")

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		follow_mouse = 1,
		touchpad = {
			natural_scroll = false,
		},
		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
	},

	general = {
		gaps_in = 4,
		gaps_out = 10,
		border_size = 2,
		-- using the gradient colors from mocha table defined in mocha.lua
		["col.active_border"] = { colors = { mocha.rosewater, mocha.pink, mocha.lavender } },
		["col.inactive_border"] = "rgba(595959aa)",

		-- Switching layout per your request!
		layout = "scrolling",
	},

	decoration = {
		rounding = 2,
		blur = {
			enabled = true,
			size = 3,
			passes = 1,
			new_optimizations = true,
			xray = true,
		},
	},

	animations = {
		enabled = true,
		-- Beziers and animations are passed as string arrays
		bezier = {
			"myBezier, 0.05, 0.9, 0.1, 1.05",
		},
		animation = {
			"windows, 1, 7, myBezier",
			"windowsOut, 1, 7, default, popin 80%",
			"border, 1, 10, default",
			"borderangle, 1, 8, default",
			"fade, 1, 7, default",
			"workspaces, 1, 6, default",
		},
	},

	scrolling = {
		-- Base setup for the scrolling layout
		focus_fit_method = 1,
		column_width = 0.5,
	},

	-- Per-device config
	device = {
		{
			name = "epic-mouse-v1",
			sensitivity = -0.5,
		},
	},
})
