hl.on("hyprland.start", function()
	hl.exec_cmd("~/.config/hypr/scripts/resetxdgportal.sh")
	hl.exec_cmd("wlsunset -t 5200 -S 9:00 -s 19:30") -- Nightligt from 7:30pm to 9am
	hl.exec_cmd("systemctl --user restart pipewire")
	hl.exec_cmd("~/.config/hypr/setwall.sh")
	hl.exec_cmd("qs")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("mullvad connect")
	hl.exec_cmd("opensnitch-ui")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
	hl.exec_cmd("hyprctl setcursor 'Miku Cursors' 24")
end)
