# WINDOW RULES
# OPACITY
windowrule = opacity 0.98 0.98, match:class ^(Brave-browser)$
windowrule = opacity 0.98 0.98, match:class ^(Firefox)$
windowrule = opacity 0.98 0.98, match:class ^(librewolf)$
windowrule = opacity 0.95 0.95, match:class ^(thunar)$

# Application placement rules
windowrule = workspace 1 silent, match:class ^(Firefox)$
windowrule = workspace 2 silent, match:class ^(vesktop)$
windowrule = workspace 3 silent, match:class ^(wezterm)$
windowrule = workspace 10 silent, match:class ^(wezterm)$

# Layer blur
layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace lockscreen

# Desktop 
#windowrulev2 = workspace 1 silent,class:^(librewolf)$
#windowrulev2 = workspace 2 silent,float,class:^(wezterm)$
#windowrulev2 = workspace 4 silent,class:^(spotify)$

